services:
  chaos:
    build:
      context: https://github.com/zipofar/uffizzi_chaos
      dockerfile: /sleeper/Dockerfile

  web:
    image: nginx

x-uffizzi:
  ingress:
    service: chaos
    port: 80

  continuous_preview:
    share_to_github: true
    delete_preview_after: 1h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
